<?php

namespace Diroute\CssEngine;

use Diroute\CssEngine\Parser\UtilityCandidate;
use Diroute\CssEngine\Rules\BorderRules;
use Diroute\CssEngine\Rules\ColorRules;
use Diroute\CssEngine\Rules\CursorRules;
use Diroute\CssEngine\Rules\FlexboxRules;
use Diroute\CssEngine\Rules\ResetRule;
use Diroute\CssEngine\Rules\SizeRules;
use Diroute\CssEngine\Rules\SpacingRules;
use Diroute\CssEngine\Variants\VariantProcessor;

class DirouteCssEngine
{
    /** @var Contract\RuleInterface[] */
    private array $rules = [];
    private VariantProcessor $variantProcessor;
    private array $generatedClasses = [];

    public function __construct()
    {
        $this->variantProcessor = new VariantProcessor();
        $this->rules = [new BorderRules(), new SpacingRules(), new FlexboxRules(), new ColorRules(), new CursorRules(), new SizeRules()];
    }

    public function registerRule(Contract\RuleInterface $rule): void
    {
        $this->rules[] = $rule;
    }

    public function processClasses(array $classes): string
    {
        foreach ($classes as $rawClass) {
            if (isset($this->generatedClasses[$rawClass])) {
                continue;
            }

            $candidate = UtilityCandidate::parse($rawClass);

            foreach ($this->rules as $rule) {
                if ($rule->supports($candidate)) {
                    $declarations = $rule->generateCss($candidate);
                    if ($declarations !== '') {
                        $this->generatedClasses[$rawClass] = $this->variantProcessor->wrapCss($candidate, $declarations);
                    }
                    break;
                }
            }
        }

        return implode(" ", $this->generatedClasses);
    }

    public function buildCssFile(string $outputPath): array
    {
        $cssContent = "/* Auto-generated by Diroute CSS Engine */\n";
        $cssContent .= implode(" ", $this->generatedClasses);

        file_put_contents($outputPath, $cssContent, LOCK_EX);

        return [
            'output_path' => $outputPath,
            'cssContent' => $cssContent
        ];
    }
}
